spring:
  application:
    name: Notification-Center
  kafka:
    topic: email-topic
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      properties:
        max.block.ms: 30000
        delivery.timeout.ms: 30000
  datasource:
    url: jdbc:postgresql://postgres:5432/notification
    username: postgres
    password: <your-pass>
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  notification:
    sms:
      path: C:/IntelliJ IDEA 2024.2.4/Notification-Center/SMS/sms.txt